//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDatos.Reserva
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_RESERVAS_PISTAS
    {
        public string fecha { get; set; }
        public string h_ini { get; set; }
        public string h_fin { get; set; }
        public int id_reserva { get; set; }
        public string pista { get; set; }
        public string email { get; set; }
        public Nullable<decimal> precio { get; set; }
        public decimal precio_hora { get; set; }
        public string actividad { get; set; }
        public string tipo_pista { get; set; }
        public string estado { get; set; }
        public string instalacion { get; set; }
    }
}
